general:
  data_dir: "./data"
  models_dir: "./models"
  state_dir: "./state"   # ← eklendi
  log_level: "INFO"



market:
  timeframe: "1h"
  lookback_days: 120   # 3-4 ay

sync:
  use_sentiment: false # RSS çok seyrek olduğu için eş-zamanlı seti aşırı daraltmasın

features:
  rsi_period: 14
  sma_fast: 20
  sma_slow: 50
  corr_window: 72

ml:
  enable: false
  # model_file: "btc_gb.joblib"  # istersen bu adı da kullanırız; şu an main.py sabit isimle bakıyor


rules:
  rsi_buy: 45
  rsi_sell: 65
  sentiment_min: 0.0     # sentiment kapalıysa zaten etkisiz
  atr_min_pct: 0.0010    # eş-zamanlı pencerede yeterli volatilite
  require_qqq_up: true   # QQQ ile uyuşuk saatleri eleyelim; US seansına odaklanır
  min_corr_qqq: 0.00     # negatif korelasyon saatlerini ele

risk:
  max_position_pct: 1.0      # tavanı aç
  position_mode: "scaled"     # istersen "full" yapabilirsin
  target_floor_pct: 0.30      # scaled modda asgari %30
  min_hold_bars: 4            # US seans bloklarında daha kısa tutabiliriz
  cooldown_bars: 3
  rebalance_threshold: 0.20
  exit_confirm_bars: 1
  taker_fee: 0.0004
  slippage: 0.0005
