# --- BTC Machine Settings ---
general:
  timezone: "Europe/Istanbul"
  data_dir: "./data"
  state_dir: "./state"
  models_dir: "./models"
  log_level: "INFO"

market:
  symbols: ["BTC/USDT"]
  timeframe: "1h"        # ccxt timeframes: 1m, 5m, 15m, 1h, 4h, 1d
  lookback_days: 365
  # Yahoo Finance tickers
  yfinance:
    qqq: "QQQ"
    dxy: "DX-Y.NYB"

features:
  rsi_period: 14
  sma_fast: 20
  sma_slow: 50
  corr_window: 72         # hours for rolling correlation BTC vs QQQ

sentiment:
  rss_feeds:
    - "https://www.coindesk.com/arc/outboundfeeds/rss/"
    - "https://cointelegraph.com/rss"
  use_newsapi: false      # set true and put your key below to use NewsAPI instead of RSS
  newsapi_key: ""         # optional
  rolling_hours: 24       # sentiment lookback window (hours)

macro:
  use_calendar: true
  pre_event_hours: 2
  post_event_minutes: 30
  # Add ICS links you trust (examples are placeholders; replace with real ICS URLs)
  ics_links: []

rules:
  rsi_buy: 30
  rsi_sell: 70
  sentiment_min: 0.2
  exit_sent_thresh: -0.5
  atr_min_pct: 0.0025
  require_qqq_up: true
  min_corr_qqq: 0.05

risk:
  taker_fee: 0.0004
  slippage: 0.0005
  max_position_pct: 0.5
  min_hold_bars: 12
  cooldown_bars: 8
  rebalance_threshold: 0.5
  exit_confirm_bars: 2

ml:
  enable: false
  horizon_hours: 4          # predict next 4h direction
  test_size: 0.2
  random_state: 42

execution:
  live: false               # paper by default
  exchange: "binance"
  api_key: ""
  api_secret: ""
