# =======================
# GENEL
# =======================
general:
  data_dir: "./data"
  models_dir: "./models"
  state_dir: "./state"
  log_level: "INFO"

# =======================
# SENKRONİZASYON (1h strict)
# =======================
sync:
  strict_1h: true         # tüm seriler 1h'e indir ve iç-kesişim
  lookback_days: 150      # yaklaşık ~5 ay
  use_sentiment: false    # devre dışı (RS/NaN sorunları azaltır)

# =======================
# ÖZELLİKLER
# =======================
features:
  rsi_period: 14
  sma_fast: 20
  sma_slow: 50
  corr_window: 48

# =======================
# KURAL PARAMETRELERİ
# =======================
rules:
  # rejim tabanı
  base_pos_bull: 0.80
  base_pos_bear: -0.10
  neutral_band: 0.08

  # momentum & MR
  mom_look: 24
  mom_bias_thr: 0.010
  overlay_mom: 0.25

  rsi_low: 40.0
  rsi_high: 60.0
  overlay_mr: 0.15

  # slope → confidence
  slope_look: 48
  slope_conf_norm: 0.004

  # FNG
  use_fng: true
  fng_bias_thr: 60.0
  fng_overlay: 0.05

  # breakout/down tetikleyicisi
  breakout_look: 72
  breakout_conf: 0.80

  # short kısıtları
  no_short_in_bull: true
  no_long_in_bear: false
  short_conf_cap: 0.35

# =======================
# RİSK / UYGULAMA
# =======================
risk:
  allow_short: true
  max_position: 0.90
  rebalance_threshold: 0.70
  decision_every_n_bars: 24
  min_hold_bars: 24
  cooldown_bars: 12

  fee: 0.0004
  slippage: 0.0005

  stop_loss_pct: 0.03
  take_profit_pct: 0.08
  trailing_stop_pct: 0.05

# =======================
# ML (opsiyonel)
# =======================
ml:
  enable: false
  blend_weight: 0.30
  feature_cols: []

# =======================
# RAPOR
# =======================
report:
  save_trades_csv: true
  save_equity_csv: true

# =======================
# MAKRO (güvenli varsayılan)
# =======================
macro:
  use_calendar: false
  ics_links: []
